version: '2.2'
services:
  django:
    environment:
      DEBUG: '{{ debug }}'

      # EMAIL_ENABLE: 'True'
      DEFAULT_FROM_EMAIL: '{{ admin_email }}'
      ACCOUNT_OPEN_SIGNUP: 'True'
      ACCOUNT_APPROVAL_REQUIRED: 'False'
      ACCOUNT_EMAIL_VERIFICATION: 'none'

      # SECRET_KEY: '{{ django_secret_key }}'

      ALLOWED_DOCUMENT_TYPES: "['.3ws', '.csv', '.doc', '.docx', '.fbx', '.gif', '.jpg', '.mmpk', '.mp4', '.pdf', '.png', '.ppt', '.pptx', '.txt', '.xls', '.xlsx', '.zip', '.sav']"
      MAX_DOCUMENT_SIZE: 2 # MB

      DEFAULT_ANONYMOUS_VIEW_PERMISSION: 'False'
      DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION: 'False'

      THEME_ACCOUNT_CONTACT_EMAIL: '{{ admin_email }}'

      MODIFY_TOPICCATEGORY: 'False'

      # Use same admin password for Geonode and Geoserver
      # GEOSERVER_ADMIN_PASSWORD: '{{ admin_pass }}'

      # PYCSW.CONFIGURATION.'metadata:main'.provider_name: '{{ orgname }}'

      # Default new maps to home location
      # Commented as it caused python errors
      # DEFAULT_MAP_CENTER_X: '{{ org_longitude | int }}'
      # DEFAULT_MAP_CENTER_Y: '{{ org_latitude | int}}'
      # DEFAULT_MAP_ZOOM: '{{ org_map_zoom }}'

      GOOGLE_API_KEY: '{{ google_key }}'
      BING_API_KEY: '{{ bing_key }}'

      DISPLAY_SOCIAL: 'False'
      DISPLAY_COMMENTS: 'False'
      DISPLAY_RATINGS: 'False'
      DISPLAY_WMS_LINKS: 'True'

      CREATE_LAYER: 'True'

      ACCOUNT_OPEN_SIGNUP: 'False'
